### ISSUE TITLE
Could you provide the pretrained models?

### ISSUE THREAD

**Issue by leminhnguyen** [nttcslab-sp/mamba-diarization#1]

**Comment by hamzaq2000** [comment]
Yeah `mamba_diar = Model.from_pretrained('idk')` from the setup notebook yields a model not found error.

**Comment by FrenchKrab** [comment]
Sadly, I think it won't be possible to upload the pretrained model checkpoints...

Oops, indeed I forgot to update that in the setup notebook ! You can just proceed to next notebook to check everything works.

**Comment by hamzaq2000** [comment]
No problem.
