### ISSUE TITLE
Questions about the model

### ISSUE THREAD

**Issue by jeremy110** [nttcslab-sp/mamba-diarization#2]
Hello, thank you for the tests in the paper. I have a few questions:

1. The paper uses WavLM; is it possible to switch to another model? I’m particularly interested in trying the upcoming NEST from NeMo (https://arxiv.org/html/2408.13106v1) (https://github.com/NVIDIA/NeMo/pull/10319), which performs better in many evaluations and is quite fast.

2. In the paper, Mamba is compared with LSTM. I saw Mamba2 or Xlstm in the code; are there any related data for those?

3. The official Mamba cannot run on CPU. Are there any plans to release a CPU-compatible version? For example, see https://github.com/Human9000/nd-Mamba2-torch.

**Comment by FrenchKrab** [comment]
Hello, thanks for your interest

1. I haven't looked into it, but it should not be that hard, if you want to use the pyannote library, then you can take a look in https://github.com/pyannote/pyannote-audio/tree/develop/pyannote/audio/models/segmentation, and compare "PyanNet" (SincNet+LSTM) and "SSeriouSS" (WavLM+LSTM) to see what needs to be changed to swap the feature extractor, it is not hard in my experience. Or you don't care about pyannote and then you can manually stack a few [ResBlock](https://github.com/nttcslab-sp/mamba-diarization/blob/master/src/plaqntt/modules/resblock.py)s (at least that's what worked for us) after you figured out how to use NEST.
2. We did preliminary experiments with XLSTM but we didn't manage to obtain competitive results so we did not dig further in that direction. I implemented Mamba2 but did not really have time to play with it, it was slower and required a beefier hardware than Mamba1 so we focused our efforts on the latter.
3. Hadnt seen this repository/project, it looks really good, taking notes :) But in our case we have no goals of providing a CPU-compatible version. I know this project exists : https://github.com/kroggen/mamba-cpu, so it might be possible to replace our mamba_ssm dependency with this modified fork, but have no idea whether it is usable or not.

**Comment by jeremy110** [comment]
Thank you for your reply.

1. I have already extracted the Fast-Conformer from NEST, and now I just waiting for NeMo to release the checkpoint. I will try this part further, and I appreciate your suggestion.
2. Understood. Also, I recently came across this repository: https://github.com/lucidrains/minGRU-pytorch, and it seems pretty good as well.
3. Got it.


I have another question I’d like to ask if it’s okay. In Pyannote 3.3, PixIT has added speech separation, but the architecture doesn’t seem to fully utilize WavLM’s features. Is there any possibility of sharing WavLM as the feature extractor (as shown in the architecture diagram on page 40 of this paper: https://www.mlmi.eng.cam.ac.uk/files/2021-2022_dissertations/effectiveness_of_ssl_representations_for_source_separation_reduced.pdf), and then performing diarization and separation in respective blocks?

![image](https://github.com/user-attachments/assets/16d3e724-5790-4e7c-8b41-8388ea279cec)

**Comment by FrenchKrab** [comment]
If I understand correctly this is more related to how the PixIT architecture could be modified, but I'm not that familiar with it / hadn't had the occasion to use it yet, so I can't help
But you should ask in the pyannote-audio repository !

**Comment by jeremy110** [comment]
Ok, thanks.
